[package]
name = "gazefilter-kalman"
version = "0.1.0"
authors = [
    "Jacob Trueb <jtrueb@northwestern.edu",
    "Michael Mauderer <michael@michaelmauderer.com>",
    "Rostyslav Bohomaz <rostyslav.db@gmail.com"
]
edition = "2021"
repository = "https://github.com/gazefilter/kalman"
license = "MIT"
readme = "README.md"
description = "Kalman and other filters from Kalman-and-Bayesian-Filters-in-Python"

[dependencies]
nalgebra = { version = "0.34", default-features = false, features = ["libm"] }
num-traits = { version = "0.2.17", default-features = false, features = [
    "libm",
] }

[dev-dependencies]
assert_approx_eq = "1.1.0"

[features]
default = ["alloc"]
alloc = []
